# Generated by Django 2.0.9 on 2019-02-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.IntegerField()),
                ('simtype', models.IntegerField()),
                ('actualleg', models.CharField(blank=True, max_length=3, null=True)),
                ('modelid', models.IntegerField()),
                ('simid', models.IntegerField()),
                ('view', models.TextField(blank=True, null=True)),
                ('maxwordscore', models.IntegerField()),
                ('fiveplusscore', models.IntegerField()),
                ('tenplusscore', models.IntegerField()),
                ('lidscore', models.IntegerField()),
                ('maxwords', models.IntegerField()),
                ('fiveplus', models.IntegerField()),
                ('tenplus', models.IntegerField()),
                ('fifteenplus', models.IntegerField()),
                ('exactmatch', models.IntegerField()),
                ('modelwords', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('modeltext', models.TextField(blank=True, null=True)),
                ('modelname', models.TextField(blank=True, null=True)),
                ('modeltype', models.TextField(blank=True, null=True)),
                ('modelcat', models.TextField(blank=True, null=True)),
                ('modelsubject', models.TextField(blank=True, null=True)),
                ('modeldesc', models.TextField(blank=True, null=True)),
                ('year1', models.CharField(blank=True, max_length=4, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('billno', models.SlugField(blank=True, max_length=100, null=True)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('statusdate', models.CharField(blank=True, max_length=75, null=True)),
                ('status', models.CharField(blank=True, max_length=75, null=True)),
                ('noideawhathisis', models.CharField(blank=True, max_length=100, null=True)),
                ('primarysponsors', models.TextField(blank=True, null=True)),
                ('cosponsors', models.TextField(blank=True, null=True)),
                ('othersponsors', models.TextField(blank=True, null=True)),
                ('billtext', models.TextField(blank=True, null=True)),
                ('billtitle', models.TextField(blank=True, null=True)),
                ('billid', models.TextField(blank=True, null=True)),
                ('textid', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
