# Generated by Django 2.0.9 on 2019-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
