# Generated by Django 2.0.9 on 2019-02-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0003_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('source_link', models.URLField()),
                ('model_source', models.CharField(max_length=200)),
                ('model_text', models.TextField()),
            ],
        ),
    ]
