# Generated by Django 2.0.9 on 2019-02-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0004_modelsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsuggestion',
            name='your_email',
            field=models.EmailField(default='mwynn@usatoday.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsuggestion',
            name='your_name',
            field=models.CharField(default='Matt Wynn', max_length=200),
            preserve_default=False,
        ),
    ]
