# Generated by Django 2.0.9 on 2019-03-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid', '0005_auto_20190219_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('model_source', models.CharField(blank=True, max_length=500, null=True)),
                ('model_text', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=500, null=True)),
                ('model_id', models.IntegerField()),
                ('source_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
